name: Generate Snake Animation

on:
  # Run workflow every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run workflow when the README.md file is updated
  push:
    paths:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Generates the snake animation and outputs it as a .svg file
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: MashiGitCat
          outputs: dist/snake.svg

      # Upload the generated .svg to the repository
      - name: Push Snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          file: dist/snake.svg

      # Optionally, add the generated snake to your README
      - name: Update README
        run: |
          echo "![GitHub Snake](./dist/snake.svg)" >> README.md
